env:
  global:
    - CONAN_REFERENCE: usul/3.1.0
    - CONAN_USERNAME: perryiv
    - CONAN_LOGIN_USERNAME: perryiv
    - CONAN_CHANNEL: stable
    - CONAN_UPLOAD: https://api.bintray.com/conan/perryiv/conan
    - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
    - CONAN_STABLE_BRANCH_PATTERN: "^master$"
    - secure: DABVR0xQB+M0m9RoumGVB53kH4gmQwYplM9FRLDgR2fHCmpOkIQjoQrVYs87N63LY6/ltMdJ8dAx8CLyUnp2EJ2fI3ZyYwPYDSGP47NCPu/Yxh/hu1jpZBBAucB5DkPGqO7/Mw1PPOWk9ovkjUiiAWE02GDJjgxswmcwIjB5KN9/eigwI3mUG/DY7ZcnsnIof/jstiK625OEs5cBgJ1/ViopQrIILNV36uPQArwPYNBqcxjVx/ehfRFBo2IcWNZ+tBfIP/2q8vtmos1RF7x4D0Z2gns9X5qVmCIc+YgbSwX43fQhaY6+OstxQmPN6kvO+Ak5UcTYDslWJgxbe+VBjD4XV6mTH9pGRD9K6+qszYGoopd5SPTcLCSY+pj45byJRWrP3DHotdlCDXz5f93MOAiUirih2dW7USZIpp6ookwGpkvsrTZV8+x+K7ogaWqRTVPY0UwfPe1ceIj1Pgn3RkJXn2BUa+BZXL3ThYvBpqoqjjXP3ouPkRC5y2DOePOaE3wKjCKNYTWOTDE+TZZUWHc6r/AmOs+nTz1UATr+Ud4lMLTxthDgSI8kUWOLR7ADuUObdHOH2zMy8wG4Q6ttQ0rxRzMD8zS3OUdlUaeFsWQbKOyyywkgJeGj2WadwEf7AbGX7OF/CjAdaj8zoeUugtjqp3BrabuMJTyj2sPyBfI=

.linux: &linux
  os: linux
  dist: xenial
  language: python
  python: '3.7'
  services:
    - docker

.osx: &osx
  os: osx
  language: generic

matrix:
  include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
    - <<: *linux
      env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9
    - <<: *linux
      env: CONAN_GCC_VERSIONS=10 CONAN_DOCKER_IMAGE=conanio/gcc10
    - <<: *osx
      osx_image: xcode11.6
      env: CONAN_APPLE_CLANG_VERSIONS=11.0

install:
  - pip3 install conan --upgrade
  - pip3 install conan_package_tools
  - conan user

script:
  - python3 build.py
