
################################################################################
#
#  Copyright (c) 2019, Perry L Miller IV
#  All rights reserved.
#  MIT License: https://opensource.org/licenses/mit-license.html
#
################################################################################

################################################################################
#
#  Continuous integration configuration file.
#
#  These references helped:
#  https://docs.travis-ci.com/user/languages/cpp/
#  https://cmake.org/cmake/help/v3.12/release/3.12.html
#  https://github.com/richelbilderbeek/travis_cpp_tutorial/blob/master/.travis.yml
#  https://stackoverflow.com/questions/41916656/how-to-use-travis-ci-to-build-modern-c-using-modern-cmake
#
################################################################################

# This flavor of linux comes with the version of cmake we need.
# We use the add_compile_definitions command in a CMakeLists.txt file.
# https://cmake.org/cmake/help/v3.12/release/3.12.html
# https://docs.travis-ci.com/user/languages/cpp/
dist: xenial

# We're compiling C++ code.
language: cpp

# We install things so we need sudo.
sudo: required

# We need gcc version 7 because we are using C++17 features.
# https://stackoverflow.com/questions/41916656/how-to-use-travis-ci-to-build-modern-c-using-modern-cmake
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

# Install what we need.
install:
- sudo pip install gcovr

# The sequence of commands that get executed.
script:

# Use the new gcc installed above:
- export CC=gcc-7
- export CXX=g++-7

# Set up Catch2 one level up so that gcovr does not analyze it too.
- pushd .
- cd ..
- export Catch2_ROOT="$(pwd)/Catch2"
- curl -L# https://github.com/catchorg/Catch2/archive/v2.9.1.tar.gz | tar xz
- cd Catch2-2.9.1
- mkdir build
- cd build
- cmake ../ -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_TESTING=OFF -DCATCH_INSTALL_DOCS=OFF -DCATCH_INSTALL_HELPERS=OFF -DCMAKE_INSTALL_PREFIX="${Catch2_ROOT}"
- cmake --build . --target install
- popd

# Now we can run our script.
- sh run_tests.sh
