################################################################################
#
#  Travis configuration file.
#
#  Pipeline results are here:
#
#    https://travis-ci.com/github/perryiv/usul
#
#  Resources:
#
#    https://docs.conan.io/en/latest/integrations/ci/travisci.html
#    https://docs.travis-ci.com/user/deployment/bintray/
#
################################################################################

env:
  global:
    - CONAN_USERNAME: perryiv
    - CONAN_CHANNEL: stable
    - CONAN_UPLOAD: https://api.bintray.com/conan/perryiv/conan
    - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
    - CONAN_STABLE_BRANCH_PATTERN: "^master$"
    - CONAN_REVISIONS_ENABLED: 1

.linux: &linux
  os: linux
  dist: xenial
  language: python
  python: '3.7'
  services:
    - docker

.osx: &osx
  os: osx
  language: generic

matrix:
  include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
    - <<: *linux
      env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9
    - <<: *linux
      env: CONAN_GCC_VERSIONS=10 CONAN_DOCKER_IMAGE=conanio/gcc10
    - <<: *osx
      osx_image: xcode12
      env: CONAN_APPLE_CLANG_VERSIONS=12.0

# install:
#   - pip3 install conan --upgrade
#   - pip3 install conan_package_tools
#   - conan user
#
# script:
#   - python3 build.py
