
################################################################################
#
#  Copyright (c) 2019, Perry L Miller IV
#  All rights reserved.
#
################################################################################

################################################################################
#
#  Continuous integration configuration file.
#
#  Sources:
#  https://docs.travis-ci.com/user/languages/cpp/
#  https://github.com/richelbilderbeek/travis_cpp_tutorial/blob/master/.travis.yml
#  https://medium.com/@manjula.cse/how-to-stop-the-execution-of-travis-pipeline-if-script-exits-with-an-error-f0e5a43206bf
#
################################################################################

language: cpp
compiler: gcc
dist: trusty
# sudo : require

# before_install:
# - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
# - sudo apt-get update -qq
#
# install:
# - sudo apt-get install -qq g++-5
- git clone https://github.com/catchorg/Catch2.git
- export CATCH2_INC_DIR=${HOME}/Catch2/single_include

script:
# - export CATCH2_INC_DIR=${HOME}/Catch2/single_include
- echo $CATCH2_INC_DIR
- ls $CATCH2_INC_DIR
- mkdir -p build || travis_terminate 1;
- cd build || travis_terminate 1;
- mkdir debug || travis_terminate 1;
- cd debug || travis_terminate 1;
- cmake ../../ -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE="Debug" || travis_terminate 1;
- cmake --build . || travis_terminate 1;
- cd bin || travis_terminate 1;
- ls -al ./usul_math_test || travis_terminate 1;
- file ./usul_math_test || travis_terminate 1;
- ./usul_math_test || travis_terminate 1;
- cd ../ || travis_terminate 1;
- mkdir release || travis_terminate 1;
- cd release || travis_terminate 1;
- cmake ../../ -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE="Release" || travis_terminate 1;
- cmake --build . || travis_terminate 1;
- cd bin || travis_terminate 1;
- ls -al ./usul_math_test || travis_terminate 1;
- file ./usul_math_test || travis_terminate 1;
- ./usul_math_test || travis_terminate 1;
