
################################################################################
#
#  Copyright (c) 2019, Perry L Miller IV
#  All rights reserved.
#
################################################################################

################################################################################
#
#  Continuous integration configuration file.
#
#  These references helped:
#  https://docs.travis-ci.com/user/languages/cpp/
#  https://github.com/richelbilderbeek/travis_cpp_tutorial/blob/master/.travis.yml
#
################################################################################

# We're compiling C++ code.
language: cpp

# For now we're only using this compiler.
compiler: gcc

# This flavor of linux comes with the version of cmake and gcc we need.
# We use the add_compile_definitions command in a CMakeLists.txt file.
# https://cmake.org/cmake/help/v3.12/release/3.12.html
# https://docs.travis-ci.com/user/languages/cpp/
dist: xenial

# The sequence of commands that get executed.
script:

- whoami
- pwd
- ls
- cmake -version
- gcc --version

- mkdir -p external/catch2
- curl https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp > external/catch2/catch.hpp
- export CATCH2_INC_DIR=`pwd`/external
- echo $CATCH2_INC_DIR
- ls $CATCH2_INC_DIR

- mkdir -p build/debug
- cd build/debug
- cmake ../../ -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE="Debug"
- cmake --build .
- ls -al ./bin/usul_math_test
- file ./bin/usul_math_test
- ./bin/usul_math_test

- cd ../
- mkdir release
- cd release
- cmake ../../ -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE="Release"
- cmake --build .
- ls -al ./bin/usul_math_test
- file ./bin/usul_math_test
- ./bin/usul_math_test
