################################################################################
#
#  Azure Pipelines configuration file.
#
#  Pipeline results are here:
#
#    https://dev.azure.com/perryiv/usul
#
#  Resources:
#
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted
#    https://medium.com/@brentrobinson5/containerised-ci-cd-pipelines-with-azure-devops-74064c679f20
#    https://github.com/conan-io/conan-docker-tools/blob/master/azure-pipelines.yml
#    https://jaylee.org/archive/2019/03/21/azure-devops-wasm-build-container.html
#    https://github.com/microsoft/azure-pipelines-agent/issues/2043
#    https://hub.docker.com/r/conanio/gcc8
#    https://hub.docker.com/_/microsoft-windows-servercore
#    https://github.com/jonico/libzengithub/blob/master/azure-pipelines.yml
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables#secret-variables
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases#timeouts
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/shell-script
#    https://github.com/actions/virtual-environments
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks
#    https://docs.conan.io/en/1.10/howtos/run_conan_in_docker.html
#    https://stackoverflow.com/questions/57411060/azure-pipeline-using-matrix-environment-variable-in-step-condition
#
################################################################################

trigger:
- master

strategy:
  matrix:

    Linux_GCC_10:
      imageName: 'ubuntu-latest'
      use_docker: 1
      docker_image: conanio/gcc10
      compiler_version: 10
      timeoutInMinutes: 120

    Linux_GCC_9:
      imageName: 'ubuntu-latest'
      use_docker: 1
      docker_image: conanio/gcc9
      compiler_version: 9
      timeoutInMinutes: 120

    Linux_GCC_8:
      imageName: 'ubuntu-latest'
      use_docker: 1
      docker_image: conanio/gcc8
      compiler_version: 8
      timeoutInMinutes: 120

    Linux_GCC_7:
      imageName: 'ubuntu-latest'
      use_docker: 1
      docker_image: conanio/gcc7
      compiler_version: 7
      timeoutInMinutes: 120

    Apple_Clang_12:
      imageName: 'macOS-10.15'
      use_docker: 0
      docker_image: ''
      compiler_version: 12.0
      timeoutInMinutes: 120

    Apple_Clang_11:
      imageName: 'macOS-10.14'
      use_docker: 0
      docker_image: ''
      compiler_version: 11.0
      timeoutInMinutes: 120

    Apple_Clang_10:
      imageName: 'macOS-10.14'
      use_docker: 0
      docker_image: ''
      compiler_version: 10.0
      timeoutInMinutes: 120

    Apple_Clang_9:
      imageName: 'macOS-10.14'
      use_docker: 0
      docker_image: ''
      compiler_version: 9.0
      timeoutInMinutes: 120

    # Visual_Studio_2019:
    #   imageName: 'windows-latest'
    #   compiler_version: 16 # Visual Studio 2019
    #   use_docker: 0
    #   timeoutInMinutes: 120

    # Visual_Studio_2017:
    #   imageName: 'windows-latest'
    #   compiler_version: 15 # Visual Studio 2017
    #   use_docker: 0
    #   timeoutInMinutes: 120

    # Windows_2016: # CMake is too old.
    #   imageName: 'vs2017-win2016' # windows-2016 does not exist.
    #   displayName: Windows 2016
    #   compiler_version: 15 # Visual Studio 2017
    #   timeoutInMinutes: 120

pool:
  vmImage: $(imageName)

variables:
  CONAN_USERNAME: perryiv
  CONAN_PASSWORD: $(SECRET_BINTRAY_PASSWORD) # Configured in Azure UI
  CONAN_CHANNEL: stable
  CONAN_UPLOAD: https://api.bintray.com/conan/perryiv/conan
  CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
  CONAN_STABLE_BRANCH_PATTERN: "^master$"
  CONAN_REVISIONS_ENABLED: 1
  CONAN_USE_DOCKER: $(use_docker)
  CONAN_DOCKER_IMAGE: $(docker_image)
  CONAN_GCC_VERSIONS: $(compiler_version)
  CONAN_APPLE_CLANG_VERSIONS: $(compiler_version)
  CONAN_VISUAL_VERSIONS: $(compiler_version)

steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"
      addToPath: true
      architecture: "x64"
    displayName: Select Python

  - script: |
      python -m pip install --upgrade pip
      pip install conan --upgrade
      pip install conan_package_tools
      conan user
    displayName: Configure Conan

  - script: |
      python --version
      pip --version
      gcc --version
      cmake --version
      conan --version
    displayName: Print Versions

  - script: |
      env
    displayName: Print Environment

  - script: |
      python build.py
    displayName: Build
