################################################################################
#
#  Azure Pipelines configuration file.
#
#  Pipeline results are here:
#
#    https://dev.azure.com/perryiv/usul
#
################################################################################

trigger:
- master

strategy:
  matrix:
    gcc8:
      imageName: 'conanio/gcc8'
    gcc9:
      imageName: 'conanio/gcc9'
    gcc10:
      imageName: 'conanio/gcc10'
    mac:
      imageName: 'macos-10.15'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- script: echo This is script number 1
  displayName: 'Script 1'

- script: |
    echo This is script number 2
    echo This is the second line
  displayName: 'Script 2'
