################################################################################
#
#  Azure Pipelines configuration file.
#
#  Pipeline results are here:
#
#    https://dev.azure.com/perryiv/usul
#
#  Resources:
#
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted
#    https://medium.com/@brentrobinson5/containerised-ci-cd-pipelines-with-azure-devops-74064c679f20
#    https://github.com/conan-io/conan-docker-tools/blob/master/azure-pipelines.yml
#    https://jaylee.org/archive/2019/03/21/azure-devops-wasm-build-container.html
#    https://github.com/microsoft/azure-pipelines-agent/issues/2043
#    https://hub.docker.com/r/conanio/gcc8
#    https://hub.docker.com/_/microsoft-windows-servercore
#    https://github.com/jonico/libzengithub/blob/master/azure-pipelines.yml
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables#secret-variables
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases#timeouts
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/shell-script
#    https://github.com/actions/virtual-environments
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks
#    https://docs.conan.io/en/1.10/howtos/run_conan_in_docker.html
#
################################################################################

trigger:
- master

strategy:
  matrix:
    GCC_10:
      imageName: 'ubuntu-latest'
      displayName: GCC 10
      gcc-version: 10
      timeoutInMinutes: 120
    GCC_9:
      imageName: 'ubuntu-latest'
      displayName: GCC 9
      gcc-version: 9
      timeoutInMinutes: 120
    GCC_8:
      imageName: 'ubuntu-latest'
      displayName: GCC 8
      gcc-version: 8
      timeoutInMinutes: 120
    GCC_7:
      imageName: 'ubuntu-latest'
      displayName: GCC 7
      gcc-version: 7
      timeoutInMinutes: 120
    Clang_12:
      imageName: 'macOS-latest'
      displayName: Clang 12
      clang-version: 12.0
      timeoutInMinutes: 120
    Clang_11:
      imageName: 'macOS-latest'
      displayName: Clang 11
      clang-version: 11.0
      timeoutInMinutes: 120
    Clang_10:
      imageName: 'macOS-latest'
      displayName: Clang 10
      clang-version: 10.0
      timeoutInMinutes: 120
    Clang_9:
      imageName: 'macOS-latest'
      displayName: Clang 9
      clang-version: 9.0
      timeoutInMinutes: 120
    Visual_Studio_2019:
      imageName: 'windows-latest'
      displayName: VC++ 2019
      vs-version: 16 # Visual Studio 2019
      timeoutInMinutes: 120
    Visual_Studio_2019:
      imageName: 'windows-latest'
      displayName: VC++ 2017
      vs-version: 15 # Visual Studio 2017
      timeoutInMinutes: 120

    # Windows_2016: # CMake is too old.
    #   imageName: 'vs2017-win2016' # windows-2016 does not exist.
    #   displayName: Windows 2016
    #   vs-version: 15 # Visual Studio 2017
    #   timeoutInMinutes: 120

pool:
  vmImage: $(imageName)

variables:
  CONAN_USERNAME: perryiv
  CONAN_PASSWORD: $(SECRET_BINTRAY_PASSWORD) # Configured in Azure UI
  CONAN_CHANNEL: stable
  CONAN_UPLOAD: https://api.bintray.com/conan/perryiv/conan
  CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
  CONAN_STABLE_BRANCH_PATTERN: "^master$"
  CONAN_REVISIONS_ENABLED: 1
  CONAN_USE_DOCKER: 1
  CONAN_VISUAL_VERSIONS: $(vs-version)
  CONAN_APPLE_CLANG_VERSIONS: $(clang-version)
  CONAN_GCC_VERSIONS: $(gcc-version)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"
      addToPath: true
      architecture: "x64"
  - script: |
      python -m pip install --upgrade pip
      pip install conan --upgrade
      pip install conan_package_tools
      conan user
    displayName: Configure
  - script: |
      python --version
      pip --version
      gcc --version
      cmake --version
      conan --version
    displayName: Versions
  - script: |
      python build.py
    displayName: Build
