################################################################################
#
#  Azure Pipelines configuration file.
#
#  Pipeline results are here:
#
#    https://dev.azure.com/perryiv/usul
#
#  Resources:
#
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases
#    https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted
#    https://medium.com/@brentrobinson5/containerised-ci-cd-pipelines-with-azure-devops-74064c679f20
#    https://github.com/conan-io/conan-docker-tools/blob/master/azure-pipelines.yml
#
################################################################################

trigger:
- master

jobs:

- job: Linux_Job
  displayName: Linux Job
  strategy:
    matrix:
      gcc8:
        imageName: 'gcc:8'
      gcc9:
        imageName: 'gcc:9'
      gcc10:
        imageName: 'gcc:10'
  pool:
    vmImage: 'ubuntu-latest'
  container: $[variables['imageName']]
  steps:
  - script: |
      apt-get install python3-pip
    displayName: 'Configure pip3'
  - script: |
      pip3 install conan --upgrade
      pip3 install conan_package_tools
      conan user
    displayName: 'Configure conan'

- job: Windows_Job
  displayName: Windows Job
  strategy:
    matrix:
      gcc8:
        imageName: 'mcr.microsoft.com/windows/servercore:ltsc2019'
  pool:
    vmImage: 'windows-latest'
  container: $[variables['imageName']]

- job: Mac_10_15
  displayName: Mac 10.15 Job
  pool:
    vmImage: 'macOS-10.15'

- job: Mac_10_14
  displayName: Mac 10.14 Job
  pool:
    vmImage: 'macOS-10.14'
